### ISSUE TITLE
Set correct value for CFBundleShortVersionString

### ISSUE THREAD

**Issue by denis15yo** [ITECOMMPAY/mobile-sdk-ios-ui#1]
Error when using Xcode Cloud:

_This bundle is invalid. The value for key CFBundleShortVersionString 'DEBUG' in the Info.plist file must be a period-separated list of at most three non-negative integers. Please find more information about CFBundleShortVersionString at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleshortversionstring_

Fixed by manually setting the correct value. Please fix this so that you don't have to manually change the Info.plist  file each time you update the library

**Comment by ArtemSerebrennikov** [comment]
Thank you for the report, should be fixed in 3.1.0
